apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium
helmCharts:
  - name: cilium
    repo: https://helm.cilium.io
    version: 1.19.6
    releaseName: cilium
    valuesFile: values.yaml
resources:
  - l2-announcement-policy.yaml
  - lb-ip-pool.yaml
  - namespace.yaml
