apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
helmCharts:
  - name: homepage
    repo: ghcr.io/m0nsterrr/helm-charts
    version: 4.13.0
    releaseName: homepage
    valuesFile: values.yaml
