ingress:
  enabled: true
  ingressClassName: "cilium"
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    external-dns.alpha.kubernetes.io/hostname: homepage.k3s.pyxo.network
    cilium.io/https-redirect: "true"
  hosts:
    - host: homepage.k3s.pyxo.network
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - homepage.k3s.pyxo.network
      secretName: homepage-tls
volumes:
  - name: homepage-configs
    configMap:
      name: homepage-configs
volumeMounts:
  - name: homepage-configs
    mountPath: /app/config/settings.yaml
    subPath: settings.yaml
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/bookmarks.yaml
    subPath: bookmarks.yaml
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/services.yaml
    subPath: services.yaml
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/widgets.yaml
    subPath: widgets.yaml
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/kubernetes.yaml
    subPath: kubernetes.yaml
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/docker.yaml
    subPath: docker.yaml
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/custom.css
    subPath: custom.css
    readOnly: true
  - name: homepage-configs
    mountPath: /app/config/custom.js
    subPath: custom.js
    readOnly: true
