apiVersion: postgres-operator.crunchydata.com/v1
kind: PostgresCluster
metadata:
  name: paperless-ngx
  namespace: paperless-ngx-data
  annotations:
    postgres-operator.crunchydata.com/autoCreateUserSchema: "true"
spec:
  postgresVersion: 18
  users:
    - name: paperless-ngx
      databases:
        - paperless-ngx
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 1Gi
  backups:
    pgbackrest:
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 1Gi
