apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: authentik
  namespace: authentik
spec:
  itemPath: vaults/k3s/items/authentik-secrets
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cluster-authentik-user
  namespace: authentik
spec:
  itemPath: vaults/k3s/items/cluster-authentik-user
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cluster-authentik-superuser
  namespace: authentik
spec:
  itemPath: vaults/k3s/items/cluster-authentik-superuser
