authentik:
  enabled: false
  existingSecret:
    secretName: "authentik-secret-key"
  postgresql:
    password: "authentik"
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: authentik.k3s.pyxo.network
      cilium.io/https-redirect: "true"
    ingressClassName: "cilium"
    hosts:
    - authentik.k3s.pyxo.network
    tls:
    - secretName: authentik.k3s.pyxo.network
      hosts:
      - autentik.k3s.pyxo.network
postgresql:
  enabled: true
  auth:
    password: "authentik"
