authentik:
  enabled: false
  existingSecret:
    secretName: "authentik-secret-key"
  postgresql:
    host: cluster-authentik-rw.authentik.svc.cluster.local
    user: file:///postgres-creds/username
    password: file:///postgres-creds/password
server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      external-dns.alpha.kubernetes.io/hostname: authentik.k3s.pyxo.network
      cilium.io/https-redirect: "true"
    ingressClassName: "cilium"
    hosts:
    - authentik.k3s.pyxo.network
    tls:
    - secretName: authentik.k3s.pyxo.network
      hosts:
      - autentik.k3s.pyxo.network
  volumes:
    - name: postgres-creds
      secret:
        secretName: cluster-authentik-user
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
worker:
  volumes:
    - name: postgres-creds
      secret:
        secretName: cluster-authentik-user
  volumeMounts:
    - name: postgres-creds
      mountPath: /postgres-creds
      readOnly: true
