apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
helmCharts:
  - name: external-dns
    repo: https://kubernetes-sigs.github.io/external-dns
    version: 1.21.1
    releaseName: external-dns
    valuesFile: values.yaml
resources:
  - opi-pihole-password.yaml
  - opi-pihole-server.yaml
  - opi-unifi-api-key.yaml
  - namespace.yaml
