apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: netbox
helmCharts:
  - name: netbox
    repo: https://charts.netbox.oss.netboxlabs.com
    version: 8.3.22
    releaseName: netbox
    valuesFile: values.yaml
