apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password
spec:
  project: infra
  destination:
    namespace: 1password
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://1password.github.io/connect-helm-charts/'
      chart: connect
      targetRevision: 2.0.2
      helm:
        valueFiles:
          - $values/values/1password.yaml
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      ref: values
      path: resources/1password
