apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
spec:
  project: apps
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: "https://charts.goauthentik.io/"
      chart: authentik
      targetRevision: 2026.5.2
      helm:
        valueFiles:
          - $values/values/authentik.yaml
    - repoURL: "https://github.com/miglis/k3s-gitops.git"
      targetRevision: main
      ref: values
