apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: infra
  destination:
    namespace: cilium
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://helm.cilium.io'
      chart: cilium
      targetRevision: 1.17.5
      helm:
        valueFiles:
          - $values/values/cilium.yaml
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      ref: values
