apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  project: infra
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://kubernetes-sigs.github.io/external-dns'
      chart: external-dns
      targetRevision: 1.19.0
      helm:
        valueFiles:
          - $values/values/external-dns.yaml
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      ref: values
      path: resources/external-dns
