apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt
spec:
  project: infra
  destination:
    namespace: kubevirt
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  sources:
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      path: resources/kubevirt
