apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: netbox
spec:
  project: apps
  destination:
    namespace: netbox
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'ghcr.io/netbox-community/netbox-chart'
      chart: netbox
      targetRevision: 6.1.0
      helm:
        valueFiles:
          - $values/values/netbox.yaml
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      ref: values
