apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: paperless-ngx
spec:
  project: apps
  destination:
    namespace: paperless-ngx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  sources:
    - path: .
      repoURL: 'oci://codeberg.org/wrenix/helm-charts/paperless-ngx'
      targetRevision: 0.3.10
      helm:
        valueFiles:
          - $values/values/paperless-ngx.yaml
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      ref: values
      path: resources/paperless-ngx
