apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: infra
  destination:
    namespace: sealed-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
  sources:
    - repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
      chart: sealed-secrets
      targetRevision: 2.17.3
      helm:
        valueFiles:
          - $values/values/sealed-secrets.yaml
    - repoURL: 'https://github.com/miglis/k3s-gitops.git'
      targetRevision: main
      ref: values
