apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: paperless-ngx
helmCharts:
  - name: paperless-ngx
    repo: oci://codeberg.org/wrenix/helm-charts
    version: 0.3.19
    releaseName: paperless-ngx
    valuesFile: values.yaml
resources:
  - postgrescluster.yaml
  - namespace.yaml
